services:
  backend:
    build: ./backend
    container_name: file-management-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/data/database.sqlite
      - JWT_SECRET=your-jwt-secret-key-change-this
      - UPLOAD_PATH=/app/data/uploads
    volumes:
      - ./data:/app/data
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: file-management-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: file-management-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/var/www/data
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  file_data:
